project:
  type: website
  output-dir: docs

website:
  title: "Sara Pedraza"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: inclusive.qmd
        text: Inclusive Science
      - href: resources.qmd
        text: Publications
      - href: posts.qmd
        text: Research

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

