project:
  type: website
  output-dir: docs

website:
  title: "Sara Pedraza"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: resources.qmd
        text: Publications
      - href: posts.qmd
        text: Inclusive Science

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

